name: Tweet Scheduler

on:
  schedule:
    # Runs every 3 hours
    - cron: "0 */3 * * *"
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  twitter-bot:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Print a test message (for debugging)
      - name: Print a message
        run: echo "Workflow triggered successfully!"


      # Step 3: Create .env file from secrets
      - name: Create .env file
        run: |
          echo "CONSUMER_KEY=${{ secrets.CONSUMER_KEY }}" >> .env
          echo "CONSUMER_SECRET=${{ secrets.CONSUMER_SECRET }}" >> .env
          echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> .env
          echo "ACCESS_SECRET=${{ secrets.ACCESS_SECRET }}" >> .env

      # Step 4: Install dependencies (if using Python)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run your Python script using the .env file
      - name: Run Twitter bot script
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        run: python your_script.py
